version: "3.9"

services:
  laravel:
    container_name: dentistclinic-laravel
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - dentistclinic-volume:/var/www/html/storage
    networks:
      - dentistclinic-network
    
  database:
    container_name: dentistclinic-db
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - dentistclinic-volume:/var/lib/mysql
    networks:
      - dentistclinic-network

volumes:
  dentistclinic-volume:
    driver: local
  dentistclinic-db-volume:
    driver: local

networks:
  dentistclinic-network:
    driver: bridge